color0 #10131a
color1 #ffb4ab
color2 #b1c6f9
color3 #e7b9d6
color4 #afd281
color5 #b1c6f9
color6 #e7b9d6
color7 #e1e2ec
color8 #8c909f
color9 #ffb4ab
color10 #b1c6f9
color11 #e7b9d6
color12 #afd281
color13 #b1c6f9
color14 #e7b9d6
color15 #e1e2ec

cursor                #e1e2ec
cursor_text_color     #10131a
background            #10131a
foreground            #e1e2ec
selection_foreground  #c2c6d6
selection_background  #424753
url_color             #afd281