secret: ''
external-ui: /etc/mihomo/ui
external-ui-name: my-ui
external-ui-url: "https://gh-proxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
external-controller: 0.0.0.0:9097
external-controller-cors:
  allow-private-network: true
  allow-origins:
    - '*'

proxy-providers:
  my-sub:
    type: http
    interval: 1800
    proxy: DIRECT
    path: ./proxy_providers/my-sub.yaml
    url: "Your sub URL"

proxy-groups:
  - name: 🚀 节点选择
    type: select
    use:
      - my-sub
    proxies:
      - DIRECT

  - name: ♻️ 自动选择
    type: url-test
    use:
      - my-sub
    url: https://www.gstatic.com/generate_204
    interval: 300
    timeout: 5000

global-ua: clash.meta
geodata-mode: false
geodate-loader: standard
geo-auto-update: false
geo-update-interval: 48
geox-url:
  geosite: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
mode: rule
redir-port: 7892
mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: true
log-level: info
unified-delay: true
tun:
  enable: false
  stack: gvisor
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
    - any:53
profile:
  store-selected: true
dns:
  use-system-hosts: false
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16

rules:
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择
